# Generated by Django 5.2.2 on 2025-06-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код услуги')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
            ],
        ),
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('partial', 'Частично оплачено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='charge',
            name='service',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='charges.servicetype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='charge',
            unique_together={('account', 'service', 'period')},
        ),
        migrations.RemoveField(
            model_name='charge',
            name='service_name',
        ),
    ]
