services:
  db:
    image: postgres:14
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      network: host  # <- если DNS не работает, временно добавьте это
    command: /app/entrypoint.sh
    volumes:
      - .:/app:cached
    ports:
      - "${WEB_PORT:-8000}:8000"
    env_file: .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

volumes:
  postgres_data:
