# Generated by Django 5.2.2 on 2025-06-11 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Номер должен состоять из 10 цифр')], verbose_name='Номер лицевого счета')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес помещения')),
                ('owner_full_name', models.CharField(max_length=150, verbose_name='ФИО владельца')),
                ('area', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Площадь (м²)')),
                ('residents_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество проживающих')),
                ('managing_company', models.CharField(max_length=150, verbose_name='Управляющая компания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный счет')),
            ],
        ),
    ]
